# Generated by Django 3.2.9 on 2021-12-06 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('correos', models.EmailField(max_length=20)),
                ('curp', models.IntegerField()),
                ('usuario', models.CharField(max_length=10)),
            ],
        ),
    ]
