# Generated by Django 3.2.9 on 2021-12-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='curp',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
