# Generated by Django 3.2.9 on 2021-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0002_auto_20211206_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='correoAsignado',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
