# Generated by Django 3.2.9 on 2021-12-06 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0003_auto_20211206_1650'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='correoAsignado',
            new_name='correo_Asignado',
        ),
    ]
