# Generated by Django 3.2.9 on 2021-12-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0004_rename_correoasignado_usuarios_correo_asignado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='contraseña',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo_Asignado',
            field=models.EmailField(max_length=40, null=True),
        ),
    ]
