# Generated by Django 3.2.9 on 2021-12-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0005_auto_20211207_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='contraseña',
            new_name='password',
        ),
    ]
