# Generated by Django 3.2.9 on 2021-12-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0006_rename_contraseña_usuarios_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='password',
            new_name='contraseña',
        ),
    ]
