# Generated by Django 3.2.9 on 2021-12-09 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paginaweb', '0007_rename_password_usuarios_contraseña'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='correos',
            new_name='correo',
        ),
    ]
